const API='https://xianjian-a-share-ai.taoxiaohui987.chatgpt.site/api';
let active={code:'600519',exchange:'SH',name:'贵州茅台'},range='日K',searchTimer;
const $=s=>document.querySelector(s),fmt=n=>Number(n).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const toast=t=>{const el=$('#toast');el.textContent=t;el.style.display='block';clearTimeout(window.tt);window.tt=setTimeout(()=>el.style.display='none',1800)};
async function json(url){const r=await fetch(url);if(!r.ok)throw new Error();return r.json()}
async function loadQuote(){
  $('#updated').textContent='正在更新实时行情…';
  try{const {quote:q}=await json(`${API}/quote?code=${active.code}`);active.name=q.name;$('#name').textContent=q.name;$('#price').textContent=fmt(q.price);const sign=q.change>=0?'+':'';$('#change').textContent=`${sign}${fmt(q.change)}　${sign}${q.changePct.toFixed(2)}%`;$('#change').className=q.change>=0?'rise-text':'fall-text';$('#updated').textContent=`${q.source} · ${q.updatedAt||'刚刚更新'} · 每30秒刷新`;$('#market-status').innerHTML='<i></i>免费实时行情已连接'}catch{$('#updated').textContent='行情源暂时繁忙，稍后自动重试';$('#market-status').textContent='数据重连中'}
}
function draw(points){const chart=$('#chart');chart.querySelectorAll('.candle').forEach(x=>x.remove());if(!points.length)return;const min=Math.min(...points.map(p=>p.low)),max=Math.max(...points.map(p=>p.high)),span=max-min||1;points.forEach((p,i)=>{const e=document.createElement('i'),up=p.close>=p.open;e.className='candle';e.style.left=`${2+i*(76/Math.max(1,points.length-1))}%`;e.style.bottom=`${12+(Math.min(p.open,p.close)-min)/span*165}px`;e.style.height=`${Math.max(2,Math.abs(p.close-p.open)/span*165)}px`;e.style.background=up?'#e25252':'#0a9f73';e.title=`${p.date} 开${p.open} 高${p.high} 低${p.low} 收${p.close}`;chart.appendChild(e)})}
async function loadHistory(){try{const h=await json(`${API}/history?code=${active.code}&range=${encodeURIComponent(range)}`);draw(h.points);$('#ma5').textContent=h.ma5?.toFixed(2)||'—';$('#ma10').textContent=h.ma10?.toFixed(2)||'—';$('#ma20').textContent=h.ma20?.toFixed(2)||'—'}catch{toast('历史行情暂时不可用')}}
async function loadIndices(){const specs=[['000001','.indices article:nth-child(1)'],['399001','.indices article:nth-child(2)'],['399006','.indices article:nth-child(3)']];await Promise.all(specs.map(async([code,sel])=>{try{const {quote:q}=await json(`${API}/quote?code=${code}`),el=$(sel);el.querySelector('b').textContent=fmt(q.price);el.querySelector('em').textContent=`${q.changePct>=0?'+':''}${q.changePct.toFixed(2)}%`}catch{}}))}
async function choose(s){active=s;$('#code').textContent=`${s.code}.${s.exchange}`;$('#name').textContent=s.name;$('#results').style.display='none';$('#search').value='';$('#price').textContent='加载中';await Promise.all([loadQuote(),loadHistory()]);toast(`已切换至 ${s.name}`)}
$('#search').addEventListener('input',e=>{clearTimeout(searchTimer);const q=e.target.value.trim(),box=$('#results');if(!q){box.style.display='none';return}box.style.display='block';box.innerHTML='<p class="searching">正在搜索全市场…</p>';searchTimer=setTimeout(async()=>{try{const p=await json(`${API}/search?q=${encodeURIComponent(q)}`);box.innerHTML=p.results.length?p.results.map(s=>`<button data-stock='${JSON.stringify(s)}'><span><b>${s.name}</b><small>${s.code}.${s.exchange} · ${s.market}</small></span><b>→</b></button>`).join(''):'<p class="searching">没有找到相关A股</p>';box.querySelectorAll('button').forEach(b=>b.onclick=()=>choose(JSON.parse(b.dataset.stock)))}catch{box.innerHTML='<p class="searching">搜索服务暂时不可用</p>'}},260)});
$('#watch').onclick=e=>{const on=e.target.textContent.includes('已');e.target.textContent=on?'☆ 加自选':'★ 已自选';toast(on?'已移出自选':'已加入自选')};
document.querySelectorAll('.ranges button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.ranges button').forEach(x=>x.classList.remove('active'));b.classList.add('active');range=b.textContent;loadHistory()});
document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const box=$('#insight');box.innerHTML=b.textContent==='AI预测'?'<label>模型结论</label><p><b>趋势预测来自历史价格的统计计算。</b>请结合公司基本面、公告和风险承受能力独立判断。</p><aside><b>风险观察</b>预测存在误差，仅供个人研究，不构成投资建议。</aside>':`<label>${b.textContent}</label><p><b>${b.textContent}模块持续完善中。</b>实时报价和历史行情已经接通，更多数据将分阶段加入。</p>`});
Promise.all([loadQuote(),loadHistory(),loadIndices()]);setInterval(loadQuote,30000);
