const stocks=[{code:'600519.SH',name:'贵州茅台',price:'1,588.50',change:'+28.40　+1.82%',score:78,signal:'偏多'},{code:'300750.SZ',name:'宁德时代',price:'268.36',change:'+6.32　+2.41%',score:82,signal:'偏多'},{code:'601318.SH',name:'中国平安',price:'47.82',change:'-0.31　-0.64%',score:55,signal:'中性'},{code:'000858.SZ',name:'五粮液',price:'131.20',change:'+1.51　+1.16%',score:71,signal:'关注'}];
const vals=[58,62,59,65,68,66,72,75,70,77,81,79,84,87,83,89,92,88,94,97,95,101,99,104,108,106,111,115,113,119,123,120,126,129,125];
const chart=document.querySelector('#chart');vals.forEach((v,i)=>{const e=document.createElement('i');e.className='candle';e.style.left=`${2+i*2.2}%`;e.style.bottom=`${12+(v-55)*1.25}px`;e.style.height=`${20+v%30}px`;e.style.background=i%4===0||i%7===0?'#0a9f73':'#e25252';chart.appendChild(e)});
const toast=t=>{const el=document.querySelector('#toast');el.textContent=t;el.style.display='block';clearTimeout(window.tt);window.tt=setTimeout(()=>el.style.display='none',1600)};
function select(s){['name','code','price','change','score','signal'].forEach(k=>document.querySelector('#'+k).textContent=s[k]);document.querySelector('.score').style.background=`conic-gradient(#0a9f73 ${s.score}%,#e6eeec 0)`;document.querySelector('#results').style.display='none';document.querySelector('#search').value='';toast(`已切换至 ${s.name}`)}
document.querySelector('#search').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase(),box=document.querySelector('#results');if(!q){box.style.display='none';return}const list=stocks.filter(s=>(s.name+s.code).toLowerCase().includes(q));box.innerHTML=list.map((s,i)=>`<button data-code="${s.code}"><span><b>${s.name}</b><small>${s.code}</small></span><b>${s.price}</b></button>`).join('');box.style.display='block';box.querySelectorAll('button').forEach(b=>b.onclick=()=>select(stocks.find(s=>s.code===b.dataset.code)))});
document.querySelector('#watch').onclick=e=>{const on=e.target.textContent.includes('已');e.target.textContent=on?'☆ 加自选':'★ 已自选';toast(on?'已移出自选':'已加入自选')};
document.querySelectorAll('.ranges button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.ranges button').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast(`已切换到${b.textContent}`)});
document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const box=document.querySelector('#insight');if(b.textContent==='AI预测'){box.innerHTML='<label>模型结论</label><p><b>短期动能转强，价格站稳 20 日均线。</b>量价配合改善，但临近前高压力区，预计未来 5 个交易日呈震荡上行结构。</p><aside><b>风险观察</b>若放量跌破关键支撑，短期上涨结构可能失效。预测仅供研究参考。</aside>'}else{box.innerHTML=`<label>${b.textContent}</label><p><b>${b.textContent}指标正在持续跟踪。</b>连接实时数据源后，将展示多维指标、变化趋势和归因结论。</p><aside><b>数据说明</b>当前为产品演示数据，不构成任何投资建议。</aside>`}});
